/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FirmaRouteImport } from './routes/firma'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPdfViewerRouteImport } from './routes/_authenticated/pdf-viewer'
import { Route as AuthenticatedImpostazioniRouteImport } from './routes/_authenticated/impostazioni'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedTrattamentiIndexRouteImport } from './routes/_authenticated/trattamenti.index'
import { Route as AuthenticatedPazientiIndexRouteImport } from './routes/_authenticated/pazienti.index'
import { Route as AuthenticatedMagazzinoIndexRouteImport } from './routes/_authenticated/magazzino.index'
import { Route as AuthenticatedConsensiIndexRouteImport } from './routes/_authenticated/consensi.index'
import { Route as ShareConsensoTokenRouteImport } from './routes/share.consenso.$token'
import { Route as AuthenticatedPazientiIdRouteImport } from './routes/_authenticated/pazienti.$id'
import { Route as AuthenticatedImpostazioniUtentiRouteImport } from './routes/_authenticated/impostazioni.utenti'
import { Route as AuthenticatedImpostazioniStudioRouteImport } from './routes/_authenticated/impostazioni.studio'
import { Route as AuthenticatedImpostazioniProfiloRouteImport } from './routes/_authenticated/impostazioni.profilo'
import { Route as AuthenticatedImpostazioniPreferenzeRouteImport } from './routes/_authenticated/impostazioni.preferenze'
import { Route as AuthenticatedImpostazioniBackupRouteImport } from './routes/_authenticated/impostazioni.backup'
import { Route as AuthenticatedPazientiIdEditRouteImport } from './routes/_authenticated/pazienti.$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmaRoute = FirmaRouteImport.update({
  id: '/firma',
  path: '/firma',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPdfViewerRoute = AuthenticatedPdfViewerRouteImport.update({
  id: '/pdf-viewer',
  path: '/pdf-viewer',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedImpostazioniRoute =
  AuthenticatedImpostazioniRouteImport.update({
    id: '/impostazioni',
    path: '/impostazioni',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrattamentiIndexRoute =
  AuthenticatedTrattamentiIndexRouteImport.update({
    id: '/trattamenti/',
    path: '/trattamenti/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPazientiIndexRoute =
  AuthenticatedPazientiIndexRouteImport.update({
    id: '/pazienti/',
    path: '/pazienti/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMagazzinoIndexRoute =
  AuthenticatedMagazzinoIndexRouteImport.update({
    id: '/magazzino/',
    path: '/magazzino/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConsensiIndexRoute =
  AuthenticatedConsensiIndexRouteImport.update({
    id: '/consensi/',
    path: '/consensi/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ShareConsensoTokenRoute = ShareConsensoTokenRouteImport.update({
  id: '/share/consenso/$token',
  path: '/share/consenso/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPazientiIdRoute = AuthenticatedPazientiIdRouteImport.update({
  id: '/pazienti/$id',
  path: '/pazienti/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedImpostazioniUtentiRoute =
  AuthenticatedImpostazioniUtentiRouteImport.update({
    id: '/utenti',
    path: '/utenti',
    getParentRoute: () => AuthenticatedImpostazioniRoute,
  } as any)
const AuthenticatedImpostazioniStudioRoute =
  AuthenticatedImpostazioniStudioRouteImport.update({
    id: '/studio',
    path: '/studio',
    getParentRoute: () => AuthenticatedImpostazioniRoute,
  } as any)
const AuthenticatedImpostazioniProfiloRoute =
  AuthenticatedImpostazioniProfiloRouteImport.update({
    id: '/profilo',
    path: '/profilo',
    getParentRoute: () => AuthenticatedImpostazioniRoute,
  } as any)
const AuthenticatedImpostazioniPreferenzeRoute =
  AuthenticatedImpostazioniPreferenzeRouteImport.update({
    id: '/preferenze',
    path: '/preferenze',
    getParentRoute: () => AuthenticatedImpostazioniRoute,
  } as any)
const AuthenticatedImpostazioniBackupRoute =
  AuthenticatedImpostazioniBackupRouteImport.update({
    id: '/backup',
    path: '/backup',
    getParentRoute: () => AuthenticatedImpostazioniRoute,
  } as any)
const AuthenticatedPazientiIdEditRoute =
  AuthenticatedPazientiIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedPazientiIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/firma': typeof FirmaRoute
  '/login': typeof LoginRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/impostazioni': typeof AuthenticatedImpostazioniRouteWithChildren
  '/pdf-viewer': typeof AuthenticatedPdfViewerRoute
  '/impostazioni/backup': typeof AuthenticatedImpostazioniBackupRoute
  '/impostazioni/preferenze': typeof AuthenticatedImpostazioniPreferenzeRoute
  '/impostazioni/profilo': typeof AuthenticatedImpostazioniProfiloRoute
  '/impostazioni/studio': typeof AuthenticatedImpostazioniStudioRoute
  '/impostazioni/utenti': typeof AuthenticatedImpostazioniUtentiRoute
  '/pazienti/$id': typeof AuthenticatedPazientiIdRouteWithChildren
  '/share/consenso/$token': typeof ShareConsensoTokenRoute
  '/consensi/': typeof AuthenticatedConsensiIndexRoute
  '/magazzino/': typeof AuthenticatedMagazzinoIndexRoute
  '/pazienti/': typeof AuthenticatedPazientiIndexRoute
  '/trattamenti/': typeof AuthenticatedTrattamentiIndexRoute
  '/pazienti/$id/edit': typeof AuthenticatedPazientiIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/firma': typeof FirmaRoute
  '/login': typeof LoginRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/impostazioni': typeof AuthenticatedImpostazioniRouteWithChildren
  '/pdf-viewer': typeof AuthenticatedPdfViewerRoute
  '/impostazioni/backup': typeof AuthenticatedImpostazioniBackupRoute
  '/impostazioni/preferenze': typeof AuthenticatedImpostazioniPreferenzeRoute
  '/impostazioni/profilo': typeof AuthenticatedImpostazioniProfiloRoute
  '/impostazioni/studio': typeof AuthenticatedImpostazioniStudioRoute
  '/impostazioni/utenti': typeof AuthenticatedImpostazioniUtentiRoute
  '/pazienti/$id': typeof AuthenticatedPazientiIdRouteWithChildren
  '/share/consenso/$token': typeof ShareConsensoTokenRoute
  '/consensi': typeof AuthenticatedConsensiIndexRoute
  '/magazzino': typeof AuthenticatedMagazzinoIndexRoute
  '/pazienti': typeof AuthenticatedPazientiIndexRoute
  '/trattamenti': typeof AuthenticatedTrattamentiIndexRoute
  '/pazienti/$id/edit': typeof AuthenticatedPazientiIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/firma': typeof FirmaRoute
  '/login': typeof LoginRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/impostazioni': typeof AuthenticatedImpostazioniRouteWithChildren
  '/_authenticated/pdf-viewer': typeof AuthenticatedPdfViewerRoute
  '/_authenticated/impostazioni/backup': typeof AuthenticatedImpostazioniBackupRoute
  '/_authenticated/impostazioni/preferenze': typeof AuthenticatedImpostazioniPreferenzeRoute
  '/_authenticated/impostazioni/profilo': typeof AuthenticatedImpostazioniProfiloRoute
  '/_authenticated/impostazioni/studio': typeof AuthenticatedImpostazioniStudioRoute
  '/_authenticated/impostazioni/utenti': typeof AuthenticatedImpostazioniUtentiRoute
  '/_authenticated/pazienti/$id': typeof AuthenticatedPazientiIdRouteWithChildren
  '/share/consenso/$token': typeof ShareConsensoTokenRoute
  '/_authenticated/consensi/': typeof AuthenticatedConsensiIndexRoute
  '/_authenticated/magazzino/': typeof AuthenticatedMagazzinoIndexRoute
  '/_authenticated/pazienti/': typeof AuthenticatedPazientiIndexRoute
  '/_authenticated/trattamenti/': typeof AuthenticatedTrattamentiIndexRoute
  '/_authenticated/pazienti/$id/edit': typeof AuthenticatedPazientiIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/firma'
    | '/login'
    | '/calendario'
    | '/dashboard'
    | '/impostazioni'
    | '/pdf-viewer'
    | '/impostazioni/backup'
    | '/impostazioni/preferenze'
    | '/impostazioni/profilo'
    | '/impostazioni/studio'
    | '/impostazioni/utenti'
    | '/pazienti/$id'
    | '/share/consenso/$token'
    | '/consensi/'
    | '/magazzino/'
    | '/pazienti/'
    | '/trattamenti/'
    | '/pazienti/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/firma'
    | '/login'
    | '/calendario'
    | '/dashboard'
    | '/impostazioni'
    | '/pdf-viewer'
    | '/impostazioni/backup'
    | '/impostazioni/preferenze'
    | '/impostazioni/profilo'
    | '/impostazioni/studio'
    | '/impostazioni/utenti'
    | '/pazienti/$id'
    | '/share/consenso/$token'
    | '/consensi'
    | '/magazzino'
    | '/pazienti'
    | '/trattamenti'
    | '/pazienti/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/firma'
    | '/login'
    | '/_authenticated/calendario'
    | '/_authenticated/dashboard'
    | '/_authenticated/impostazioni'
    | '/_authenticated/pdf-viewer'
    | '/_authenticated/impostazioni/backup'
    | '/_authenticated/impostazioni/preferenze'
    | '/_authenticated/impostazioni/profilo'
    | '/_authenticated/impostazioni/studio'
    | '/_authenticated/impostazioni/utenti'
    | '/_authenticated/pazienti/$id'
    | '/share/consenso/$token'
    | '/_authenticated/consensi/'
    | '/_authenticated/magazzino/'
    | '/_authenticated/pazienti/'
    | '/_authenticated/trattamenti/'
    | '/_authenticated/pazienti/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  FirmaRoute: typeof FirmaRoute
  LoginRoute: typeof LoginRoute
  ShareConsensoTokenRoute: typeof ShareConsensoTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firma': {
      id: '/firma'
      path: '/firma'
      fullPath: '/firma'
      preLoaderRoute: typeof FirmaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pdf-viewer': {
      id: '/_authenticated/pdf-viewer'
      path: '/pdf-viewer'
      fullPath: '/pdf-viewer'
      preLoaderRoute: typeof AuthenticatedPdfViewerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/impostazioni': {
      id: '/_authenticated/impostazioni'
      path: '/impostazioni'
      fullPath: '/impostazioni'
      preLoaderRoute: typeof AuthenticatedImpostazioniRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trattamenti/': {
      id: '/_authenticated/trattamenti/'
      path: '/trattamenti'
      fullPath: '/trattamenti/'
      preLoaderRoute: typeof AuthenticatedTrattamentiIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pazienti/': {
      id: '/_authenticated/pazienti/'
      path: '/pazienti'
      fullPath: '/pazienti/'
      preLoaderRoute: typeof AuthenticatedPazientiIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/magazzino/': {
      id: '/_authenticated/magazzino/'
      path: '/magazzino'
      fullPath: '/magazzino/'
      preLoaderRoute: typeof AuthenticatedMagazzinoIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/consensi/': {
      id: '/_authenticated/consensi/'
      path: '/consensi'
      fullPath: '/consensi/'
      preLoaderRoute: typeof AuthenticatedConsensiIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/share/consenso/$token': {
      id: '/share/consenso/$token'
      path: '/share/consenso/$token'
      fullPath: '/share/consenso/$token'
      preLoaderRoute: typeof ShareConsensoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pazienti/$id': {
      id: '/_authenticated/pazienti/$id'
      path: '/pazienti/$id'
      fullPath: '/pazienti/$id'
      preLoaderRoute: typeof AuthenticatedPazientiIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/impostazioni/utenti': {
      id: '/_authenticated/impostazioni/utenti'
      path: '/utenti'
      fullPath: '/impostazioni/utenti'
      preLoaderRoute: typeof AuthenticatedImpostazioniUtentiRouteImport
      parentRoute: typeof AuthenticatedImpostazioniRoute
    }
    '/_authenticated/impostazioni/studio': {
      id: '/_authenticated/impostazioni/studio'
      path: '/studio'
      fullPath: '/impostazioni/studio'
      preLoaderRoute: typeof AuthenticatedImpostazioniStudioRouteImport
      parentRoute: typeof AuthenticatedImpostazioniRoute
    }
    '/_authenticated/impostazioni/profilo': {
      id: '/_authenticated/impostazioni/profilo'
      path: '/profilo'
      fullPath: '/impostazioni/profilo'
      preLoaderRoute: typeof AuthenticatedImpostazioniProfiloRouteImport
      parentRoute: typeof AuthenticatedImpostazioniRoute
    }
    '/_authenticated/impostazioni/preferenze': {
      id: '/_authenticated/impostazioni/preferenze'
      path: '/preferenze'
      fullPath: '/impostazioni/preferenze'
      preLoaderRoute: typeof AuthenticatedImpostazioniPreferenzeRouteImport
      parentRoute: typeof AuthenticatedImpostazioniRoute
    }
    '/_authenticated/impostazioni/backup': {
      id: '/_authenticated/impostazioni/backup'
      path: '/backup'
      fullPath: '/impostazioni/backup'
      preLoaderRoute: typeof AuthenticatedImpostazioniBackupRouteImport
      parentRoute: typeof AuthenticatedImpostazioniRoute
    }
    '/_authenticated/pazienti/$id/edit': {
      id: '/_authenticated/pazienti/$id/edit'
      path: '/edit'
      fullPath: '/pazienti/$id/edit'
      preLoaderRoute: typeof AuthenticatedPazientiIdEditRouteImport
      parentRoute: typeof AuthenticatedPazientiIdRoute
    }
  }
}

interface AuthenticatedImpostazioniRouteChildren {
  AuthenticatedImpostazioniBackupRoute: typeof AuthenticatedImpostazioniBackupRoute
  AuthenticatedImpostazioniPreferenzeRoute: typeof AuthenticatedImpostazioniPreferenzeRoute
  AuthenticatedImpostazioniProfiloRoute: typeof AuthenticatedImpostazioniProfiloRoute
  AuthenticatedImpostazioniStudioRoute: typeof AuthenticatedImpostazioniStudioRoute
  AuthenticatedImpostazioniUtentiRoute: typeof AuthenticatedImpostazioniUtentiRoute
}

const AuthenticatedImpostazioniRouteChildren: AuthenticatedImpostazioniRouteChildren =
  {
    AuthenticatedImpostazioniBackupRoute: AuthenticatedImpostazioniBackupRoute,
    AuthenticatedImpostazioniPreferenzeRoute:
      AuthenticatedImpostazioniPreferenzeRoute,
    AuthenticatedImpostazioniProfiloRoute:
      AuthenticatedImpostazioniProfiloRoute,
    AuthenticatedImpostazioniStudioRoute: AuthenticatedImpostazioniStudioRoute,
    AuthenticatedImpostazioniUtentiRoute: AuthenticatedImpostazioniUtentiRoute,
  }

const AuthenticatedImpostazioniRouteWithChildren =
  AuthenticatedImpostazioniRoute._addFileChildren(
    AuthenticatedImpostazioniRouteChildren,
  )

interface AuthenticatedPazientiIdRouteChildren {
  AuthenticatedPazientiIdEditRoute: typeof AuthenticatedPazientiIdEditRoute
}

const AuthenticatedPazientiIdRouteChildren: AuthenticatedPazientiIdRouteChildren =
  {
    AuthenticatedPazientiIdEditRoute: AuthenticatedPazientiIdEditRoute,
  }

const AuthenticatedPazientiIdRouteWithChildren =
  AuthenticatedPazientiIdRoute._addFileChildren(
    AuthenticatedPazientiIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedImpostazioniRoute: typeof AuthenticatedImpostazioniRouteWithChildren
  AuthenticatedPdfViewerRoute: typeof AuthenticatedPdfViewerRoute
  AuthenticatedPazientiIdRoute: typeof AuthenticatedPazientiIdRouteWithChildren
  AuthenticatedConsensiIndexRoute: typeof AuthenticatedConsensiIndexRoute
  AuthenticatedMagazzinoIndexRoute: typeof AuthenticatedMagazzinoIndexRoute
  AuthenticatedPazientiIndexRoute: typeof AuthenticatedPazientiIndexRoute
  AuthenticatedTrattamentiIndexRoute: typeof AuthenticatedTrattamentiIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedImpostazioniRoute: AuthenticatedImpostazioniRouteWithChildren,
  AuthenticatedPdfViewerRoute: AuthenticatedPdfViewerRoute,
  AuthenticatedPazientiIdRoute: AuthenticatedPazientiIdRouteWithChildren,
  AuthenticatedConsensiIndexRoute: AuthenticatedConsensiIndexRoute,
  AuthenticatedMagazzinoIndexRoute: AuthenticatedMagazzinoIndexRoute,
  AuthenticatedPazientiIndexRoute: AuthenticatedPazientiIndexRoute,
  AuthenticatedTrattamentiIndexRoute: AuthenticatedTrattamentiIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  FirmaRoute: FirmaRoute,
  LoginRoute: LoginRoute,
  ShareConsensoTokenRoute: ShareConsensoTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
